enum ErrorCode {
	GENERIC = "GENERIC",
	ALREADY_CONNECTING = "ALREADY_CONNECTING",
	ALREADY_CONNECTED = "ALREADY_CONNECTED",
	NOT_CONNECTED = "NOT_CONNECTED",
	FILE_NOT_FOUND = "FILE_NOT_FOUND",
	FILE_ALREADY_EXISTS = "FILE_ALREADY_EXISTS",
	INVALID_FILENAME = "INVALID_FILENAME",
	INVALID_FILETYPE = "INVALID_FILETYPE",
	REQUEST_PENDING = "REQUEST_PENDING",
}

enum SuccessCode {
	OK = "OK",
	FILE_TRANSFER_OK = "FILE_TRANSFER_OK",
}

export {ErrorCode, SuccessCode};